(function(){var w,H,I,x,J,K,L,M,N,O,P,Q,y,p,z,R,S,T,U,V,W;P=function(b){var a,c;c=[];for(a in b)c.push(a);return 0===c.length};y=function(b,a){return b.push.apply(b,a)};V=function(b,a){var c,e,f,d,g;d=b.split("");g=[];e=0;for(f=d.length;e<f;e++)c=d[e],g.push(a[c]||c);return g.join("")};R=function(b,a){var c,e,f,d;d=[];c=0;for(e=a.length;c<e;c++)f=a[c],y(d,f(b));return d.sort(function(a,b){return a.i-b.i||a.j-b.j})};N=function(b,a){var c,e,f,d,g,h,j,i,k,l,m;l=[];d=b.length;h=b.toLowerCase();for(c=
f=0;0<=d?f<d:f>d;c=0<=d?++f:--f){e=g=i=c;for(k=d;i<=k?g<k:g>k;e=i<=k?++g:--g)if(h.slice(c,+e+1||9E9)in a)m=h.slice(c,+e+1||9E9),j=a[m],l.push({pattern:"dictionary",i:c,j:e,token:b.slice(c,+e+1||9E9),matched_word:m,rank:j})}return l};I=function(b){var a,c,e,f,d;f={};a=1;c=0;for(e=b.length;c<e;c++)d=b[c],f[d]=a,a+=1;return f};H=function(b,a){return function(c){var e,f,d;d=N(c,a);c=0;for(e=d.length;c<e;c++)f=d[c],f.dictionary_name=b;return d}};z={a:["4","@"],b:["8"],c:["(","{","[","<"],e:["3"],g:["6",
"9"],i:["1","!","|"],l:["1","|","7"],o:["0"],s:["$","5"],t:["+","7"],x:["%"],z:["2"]};S=function(b){var a,c,e,f,d;f={};d=b.split("");a=0;for(c=d.length;a<c;a++)b=d[a],f[b]=!0;b={};for(e in z){c=z[e];var g=d=void 0,h=void 0,h=[],g=0;for(d=c.length;g<d;g++)a=c[g],a in f&&h.push(a);a=h;0<a.length&&(b[e]=a)}return b};Q=function(b){var a,c,e,f,d,g,h,j,i,k,l,m,q;d=function(){var a;a=[];for(f in b)a.push(f);return a}();q=[[]];c=function(a){var b,c,d,e,g,j,h,i;c=[];j={};d=0;for(g=a.length;d<g;d++)h=a[d],
b=function(){var a,b,c;c=[];i=b=0;for(a=h.length;b<a;i=++b)f=h[i],c.push([f,i]);return c}(),b.sort(),e=function(){var a,c,d;d=[];i=c=0;for(a=b.length;c<a;i=++c)f=b[i],d.push(f+","+i);return d}().join("-"),e in j||(j[e]=!0,c.push(h));return c};e=function(a){var d,f,g,i,h,j,k,l,m,n,p,r,t;if(a.length){f=a[0];r=a.slice(1);l=[];n=b[f];a=0;for(h=n.length;a<h;a++){i=n[a];k=0;for(j=q.length;k<j;k++){t=q[k];d=-1;g=m=0;for(p=t.length;0<=p?m<p:m>p;g=0<=p?++m:--m)if(t[g][0]===i){d=g;break}-1===d?(d=t.concat([[i,
f]]),l.push(d)):(g=t.slice(0),g.splice(d,1),g.push([i,f]),l.push(t),l.push(g))}}q=c(l);return e(r)}};e(d);m=[];d=0;for(h=q.length;d<h;d++){k=q[d];l={};i=0;for(j=k.length;i<j;i++)a=k[i],g=a[0],a=a[1],l[g]=a;m.push(l)}return m};U=function(b,a,c){var e,f,d,g,h,j,i,k,l,m,q,o,n;q=[];for(j=0;j<b.length-1;){i=j+1;l=null;for(o=n=0;;){e=b.charAt(i-1);h=!1;g=-1;f=a[e]||[];if(i<b.length){d=b.charAt(i);k=0;for(m=f.length;k<m;k++)if(e=f[k],g+=1,e&&-1!==e.indexOf(d)){h=!0;1===e.indexOf(d)&&(o+=1);l!==g&&(n+=1,
l=g);break}}if(h)i+=1;else{2<i-j&&q.push({pattern:"spatial",i:j,j:i-1,token:b.slice(j,i),graph:c,turns:n,shifted_count:o});j=i;break}}}return q};w={lower:"abcdefghijklmnopqrstuvwxyz",upper:"ABCDEFGHIJKLMNOPQRSTUVWXYZ",digits:"01234567890"};T=function(b,a){var c,e;e=[];for(c=1;1<=a?c<=a:c>=a;1<=a?++c:--c)e.push(b);return e.join("")};p=function(b,a){var c,e;for(e=[];;){c=b.match(a);if(!c)break;c.i=c.index;c.j=c.index+c[0].length-1;e.push(c);b=b.replace(c[0],T(" ",c[0].length))}return e};O=/\d{3,}/;
W=/19\d\d|200\d|201\d/;M=function(b){var a,c,e,f,d,g,h,j,i,k,l,m,q,o;f=[];q=p(b,/\d{4,8}/);j=0;for(i=q.length;j<i;j++){g=q[j];h=[g.i,g.j];g=h[0];h=h[1];e=b.slice(g,+h+1||9E9);a=e.length;c=[];6>=e.length&&(c.push({daymonth:e.slice(2),year:e.slice(0,2),i:g,j:h}),c.push({daymonth:e.slice(0,a-2),year:e.slice(a-2),i:g,j:h}));6<=e.length&&(c.push({daymonth:e.slice(4),year:e.slice(0,4),i:g,j:h}),c.push({daymonth:e.slice(0,a-4),year:e.slice(a-4),i:g,j:h}));e=[];l=0;for(k=c.length;l<k;l++)switch(a=c[l],a.daymonth.length){case 2:e.push({day:a.daymonth[0],
month:a.daymonth[1],year:a.year,i:a.i,j:a.j});break;case 3:e.push({day:a.daymonth.slice(0,2),month:a.daymonth[2],year:a.year,i:a.i,j:a.j});e.push({day:a.daymonth[0],month:a.daymonth.slice(1,3),year:a.year,i:a.i,j:a.j});break;case 4:e.push({day:a.daymonth.slice(0,2),month:a.daymonth.slice(2,4),year:a.year,i:a.i,j:a.j})}k=0;for(c=e.length;k<c;k++)a=e[k],d=parseInt(a.day),m=parseInt(a.month),o=parseInt(a.year),d=x(d,m,o),l=d[0],o=d[1],d=o[0],m=o[1],o=o[2],l&&f.push({pattern:"date",i:a.i,j:a.j,token:b.slice(g,
+h+1||9E9),separator:"",day:d,month:m,year:o})}return f};K=/(\d{1,2})(\s|-|\/|\\|_|\.)(\d{1,2})\2(19\d{2}|200\d|201\d|\d{2})/;J=/(19\d{2}|200\d|201\d|\d{2})(\s|-|\/|\\|_|\.)(\d{1,2})\2(\d{1,2})/;L=function(b){var a,c,e,f,d,g,h,j,i,k;g=[];j=p(b,K);e=0;for(f=j.length;e<f;e++)d=j[e],i=function(){var a,b,e,f;e=[1,3,4];f=[];b=0;for(a=e.length;b<a;b++)c=e[b],f.push(parseInt(d[c]));return f}(),d.day=i[0],d.month=i[1],d.year=i[2],d.sep=d[2],g.push(d);j=p(b,J);f=0;for(e=j.length;f<e;f++)d=j[f],i=function(){var a,
b,e,f;e=[4,3,1];f=[];b=0;for(a=e.length;b<a;b++)c=e[b],f.push(parseInt(d[c]));return f}(),d.day=i[0],d.month=i[1],d.year=i[2],d.sep=d[2],g.push(d);j=[];f=0;for(e=g.length;f<e;f++)d=g[f],a=x(d.day,d.month,d.year),i=a[0],k=a[1],a=k[0],h=k[1],k=k[2],i&&j.push({pattern:"date",i:d.i,j:d.j,token:b.slice(d.i,+d.j+1||9E9),separator:d.sep,day:a,month:h,year:k});return j};x=function(b,a,c){12<=a&&31>=a&&12>=b&&(a=[a,b],b=a[0],a=a[1]);return 31<b||12<a||!(1900<=c&&2019>=c)?[!1,[]]:[!0,[b,a,c]]};var X,Y,Z,$,
B,aa,ba,ca,da,ea,fa,ga,ha,ia,n,ja,u,ka,C,la,ma,na;u=function(b,a){var c,e,f;if(a>b)return 0;if(0===a)return 1;for(c=e=f=1;1<=a?e<=a:e>=a;c=1<=a?++e:--e)f*=b,f/=c,b-=1;return f};n=function(b){return Math.log(b)/Math.log(2)};ja=function(b,a){var c,e,f,d,g,h,j,i,k,l,m;e=B(b);m=[];c=[];d=h=0;for(l=b.length;0<=l?h<l:h>l;d=0<=l?++h:--h){m[d]=(m[d-1]||0)+n(e);c[d]=null;i=0;for(j=a.length;i<j;i++)k=a[i],k.j===d&&(g=[k.i,k.j],f=g[0],g=g[1],f=(m[f-1]||0)+aa(k),f<m[g]&&(m[g]=f,c[g]=k))}h=[];for(d=b.length-1;0<=
d;)(k=c[d])?(h.push(k),d=k.i-1):d-=1;h.reverse();j=function(a,c){return{pattern:"bruteforce",i:a,j:c,token:b.slice(a,+c+1||9E9),entropy:n(Math.pow(e,c-a+1)),cardinality:e}};d=0;i=[];l=0;for(c=h.length;l<c;l++)k=h[l],g=[k.i,k.j],f=g[0],g=g[1],0<f-d&&i.push(j(d,f-1)),d=g+1,i.push(k);d<b.length&&i.push(j(d,b.length-1));h=i;k=m[b.length-1]||0;d=ga(k);return{password:b,entropy:C(k,3),match_sequence:h,crack_time:C(d,3),crack_time_display:fa(d),score:ba(d)}};C=function(b,a){return Math.round(b*Math.pow(10,
a))/Math.pow(10,a)};ga=function(b){return 5.0E-5*Math.pow(2,b)};ba=function(b){return b<Math.pow(10,2)?0:b<Math.pow(10,4)?1:b<Math.pow(10,6)?2:b<Math.pow(10,8)?3:4};aa=function(b){var a;if(null!=b.entropy)return b.entropy;a=function(){switch(b.pattern){case "repeat":return ka;case "sequence":return la;case "digits":return ea;case "year":return na;case "date":return ca;case "spatial":return ma;case "dictionary":return da}}();return b.entropy=a(b)};ka=function(b){var a;a=B(b.token);return n(a*b.token.length)};
la=function(b){var a;a=b.token.charAt(0);a="a"===a||"1"===a?1:a.match(/\d/)?n(10):a.match(/[a-z]/)?n(26):n(26)+1;b.ascending||(a+=1);return a+n(b.token.length)};ea=function(b){return n(Math.pow(10,b.token.length))};na=function(){return n(119)};ca=function(b){var a;a=100>b.year?n(37200):n(44268);b.separator&&(a+=2);return a};ma=function(b){var a,c,e,f,d,g,h,j,i,k;"qwerty"===(e=b.graph)||"dvorak"===e?(i=oa,c=pa):(i=qa,c=ra);h=0;a=b.token.length;k=b.turns;for(e=d=2;2<=a?d<=a:d>=a;e=2<=a?++d:--d){j=Math.min(k,
e-1);for(f=g=1;1<=j?g<=j:g>=j;f=1<=j?++g:--g)h+=u(e-1,f-1)*i*Math.pow(c,f)}c=n(h);if(b.shifted_count){a=b.shifted_count;b=b.token.length-b.shifted_count;e=f=h=0;for(d=Math.min(a,b);0<=d?f<=d:f>=d;e=0<=d?++f:--f)h+=u(a+b,e);c+=n(h)}return c};da=function(b){b.base_entropy=n(b.rank);b.uppercase_entropy=ia(b);b.l33t_entropy=ha(b);return b.base_entropy+b.uppercase_entropy+b.l33t_entropy};$=/^[A-Z][^A-Z]+$/;Z=/^[^A-Z]+[A-Z]$/;Y=/^[^a-z]+$/;X=/^[^A-Z]+$/;ia=function(b){var a,c,e,f,d,g,h;h=b.token;if(h.match(X))return 0;
e=[$,Z,Y];b=0;for(a=e.length;b<a;b++)if(f=e[b],h.match(f))return 1;a=function(){var a,b,d,e;d=h.split("");e=[];b=0;for(a=d.length;b<a;b++)c=d[b],c.match(/[A-Z]/)&&e.push(c);return e}().length;b=function(){var a,b,d,e;d=h.split("");e=[];b=0;for(a=d.length;b<a;b++)c=d[b],c.match(/[a-z]/)&&e.push(c);return e}().length;e=f=d=0;for(g=Math.min(a,b);0<=g?f<=g:f>=g;e=0<=g?++f:--f)d+=u(a+b,e);return n(d)};ha=function(b){var a,c,e,f,d,g,h,j,i,k;if(!b.l33t)return 0;g=0;h=b.sub;for(i in h){k=h[i];a=function(){var a,
d,c,f;c=b.token.split("");f=[];a=0;for(d=c.length;a<d;a++)e=c[a],e===i&&f.push(e);return f}().length;c=function(){var a,d,c,f;c=b.token.split("");f=[];a=0;for(d=c.length;a<d;a++)e=c[a],e===k&&f.push(e);return f}().length;f=d=0;for(j=Math.min(c,a);0<=j?d<=j:d>=j;f=0<=j?++d:--d)g+=u(c+a,f)}return n(g)||1};B=function(b){var a,c,e,f,d,g,h,j;d=[!1,!1,!1,!1,!1];f=d[0];j=d[1];c=d[2];h=d[3];d=d[4];g=b.split("");b=0;for(e=g.length;b<e;b++)a=g[b],a=a.charCodeAt(0),48<=a&&57>=a?c=!0:65<=a&&90>=a?j=!0:97<=a&&
122>=a?f=!0:127>=a?h=!0:d=!0;b=0;c&&(b+=10);j&&(b+=26);f&&(b+=26);h&&(b+=33);d&&(b+=100);return b};fa=function(b){return 60>b?"instant":3600>b?1+Math.ceil(b/60)+" minutes":86400>b?1+Math.ceil(b/3600)+" hours":2678400>b?1+Math.ceil(b/86400)+" days":32140800>b?1+Math.ceil(b/2678400)+" months":321408E4>b?1+Math.ceil(b/32140800)+" years":"centuries"};var D={"!":["`~",null,null,"2@","qQ",null],'"':[";:","[{","]}",null,null,"/?"],"#":["2@",null,null,"4$","eE","wW"],$:["3#",null,null,"5%","rR","eE"],"%":["4$",
null,null,"6^","tT","rR"],"&":["6^",null,null,"8*","uU","yY"],"'":[";:","[{","]}",null,null,"/?"],"(":["8*",null,null,"0)","oO","iI"],")":["9(",null,null,"-_","pP","oO"],"*":["7&",null,null,"9(","iI","uU"],"+":["-_",null,null,null,"]}","[{"],",":["mM","kK","lL",".>",null,null],"-":["0)",null,null,"=+","[{","pP"],".":[",<","lL",";:","/?",null,null],"/":[".>",";:","'\"",null,null,null],"0":["9(",null,null,"-_","pP","oO"],1:["`~",null,null,"2@","qQ",null],2:["1!",null,null,"3#","wW","qQ"],3:["2@",null,
null,"4$","eE","wW"],4:["3#",null,null,"5%","rR","eE"],5:["4$",null,null,"6^","tT","rR"],6:["5%",null,null,"7&","yY","tT"],7:["6^",null,null,"8*","uU","yY"],8:["7&",null,null,"9(","iI","uU"],9:["8*",null,null,"0)","oO","iI"],":":"lL,pP,[{,'\",/?,.>".split(","),";":"lL,pP,[{,'\",/?,.>".split(","),"<":["mM","kK","lL",".>",null,null],"=":["-_",null,null,null,"]}","[{"],">":[",<","lL",";:","/?",null,null],"?":[".>",";:","'\"",null,null,null],"@":["1!",null,null,"3#","wW","qQ"],A:[null,"qQ","wW","sS",
"zZ",null],B:["vV","gG","hH","nN",null,null],C:["xX","dD","fF","vV",null,null],D:"sS,eE,rR,fF,cC,xX".split(","),E:"wW,3#,4$,rR,dD,sS".split(","),F:"dD,rR,tT,gG,vV,cC".split(","),G:"fF,tT,yY,hH,bB,vV".split(","),H:"gG,yY,uU,jJ,nN,bB".split(","),I:"uU,8*,9(,oO,kK,jJ".split(","),J:"hH,uU,iI,kK,mM,nN".split(","),K:"jJ iI oO lL ,< mM".split(" "),L:"kK oO pP ;: .> ,<".split(" "),M:["nN","jJ","kK",",<",null,null],N:["bB","hH","jJ","mM",null,null],O:"iI,9(,0),pP,lL,kK".split(","),P:"oO,0),-_,[{,;:,lL".split(","),
Q:[null,"1!","2@","wW","aA",null],R:"eE,4$,5%,tT,fF,dD".split(","),S:"aA,wW,eE,dD,xX,zZ".split(","),T:"rR,5%,6^,yY,gG,fF".split(","),U:"yY,7&,8*,iI,jJ,hH".split(","),V:["cC","fF","gG","bB",null,null],W:"qQ,2@,3#,eE,sS,aA".split(","),X:["zZ","sS","dD","cC",null,null],Y:"tT,6^,7&,uU,hH,gG".split(","),Z:[null,"aA","sS","xX",null,null],"[":"pP,-_,=+,]},'\",;:".split(","),"\\":["]}",null,null,null,null,null],"]":["[{","=+",null,"\\|",null,"'\""],"^":["5%",null,null,"7&","yY","tT"],_:["0)",null,null,"=+",
"[{","pP"],"`":[null,null,null,"1!",null,null],a:[null,"qQ","wW","sS","zZ",null],b:["vV","gG","hH","nN",null,null],c:["xX","dD","fF","vV",null,null],d:"sS,eE,rR,fF,cC,xX".split(","),e:"wW,3#,4$,rR,dD,sS".split(","),f:"dD,rR,tT,gG,vV,cC".split(","),g:"fF,tT,yY,hH,bB,vV".split(","),h:"gG,yY,uU,jJ,nN,bB".split(","),i:"uU,8*,9(,oO,kK,jJ".split(","),j:"hH,uU,iI,kK,mM,nN".split(","),k:"jJ iI oO lL ,< mM".split(" "),l:"kK oO pP ;: .> ,<".split(" "),m:["nN","jJ","kK",",<",null,null],n:["bB","hH","jJ","mM",
null,null],o:"iI,9(,0),pP,lL,kK".split(","),p:"oO,0),-_,[{,;:,lL".split(","),q:[null,"1!","2@","wW","aA",null],r:"eE,4$,5%,tT,fF,dD".split(","),s:"aA,wW,eE,dD,xX,zZ".split(","),t:"rR,5%,6^,yY,gG,fF".split(","),u:"yY,7&,8*,iI,jJ,hH".split(","),v:["cC","fF","gG","bB",null,null],w:"qQ,2@,3#,eE,sS,aA".split(","),x:["zZ","sS","dD","cC",null,null],y:"tT,6^,7&,uU,hH,gG".split(","),z:[null,"aA","sS","xX",null,null],"{":"pP,-_,=+,]},'\",;:".split(","),"|":["]}",null,null,null,null,null],"}":["[{","=+",null,
"\\|",null,"'\""],"~":[null,null,null,"1!",null,null]},E={"*":["/",null,null,null,"-","+","9","8"],"+":["9","*","-",null,null,null,null,"6"],"-":["*",null,null,null,null,null,"+","9"],".":["0","2","3",null,null,null,null,null],"/":[null,null,null,null,"*","9","8","7"],"0":[null,"1","2","3",".",null,null,null],1:[null,null,"4","5","2","0",null,null],2:["1","4","5","6","3",".","0",null],3:["2","5","6",null,null,null,".","0"],4:[null,null,"7","8","5","2","1",null],5:"4,7,8,9,6,3,2,1".split(","),6:["5",
"8","9","+",null,null,"3","2"],7:[null,null,null,"/","8","5","4",null],8:["7",null,"/","*","9","6","5","4"],9:["8","/","*","-","+",null,"6","5"]},F,pa,oa,ra,qa,sa,r,v,G;sa=[function(b){var a,c,e,f,d,g,h,j,i,k,l,m,n,o,p,s;k=[];m=Q(S(b));e=0;for(f=m.length;e<f;e++){o=m[e];if(P(o))break;h=0;for(d=DICTIONARY_MATCHERS.length;h<d;h++){g=DICTIONARY_MATCHERS[h];j=V(b,o);n=g(j);l=0;for(g=n.length;l<g;l++)if(j=n[l],s=b.slice(j.i,+j.j+1||9E9),s.toLowerCase()!==j.matched_word){i={};for(p in o)a=o[p],-1!==s.indexOf(p)&&
(i[p]=a);j.l33t=!0;j.token=s;j.sub=i;s=j;var A=void 0,A=[];for(c in i)a=i[c],A.push(c+" -> "+a);s.sub_display=A.join(", ");k.push(j)}}}return k},function(b){var a,c,e,f,d,g;d=p(b,O);g=[];e=0;for(f=d.length;e<f;e++)a=d[e],c=[a.i,a.j],a=c[0],c=c[1],g.push({pattern:"digits",i:a,j:c,token:b.slice(a,+c+1||9E9)});return g},function(b){var a,c,e,f,d,g;d=p(b,W);g=[];e=0;for(f=d.length;e<f;e++)a=d[e],c=[a.i,a.j],a=c[0],c=c[1],g.push({pattern:"year",i:a,j:c,token:b.slice(a,+c+1||9E9)});return g},function(b){return M(b).concat(L(b))},
function(b){var a,c,e;e=[];for(a=0;a<b.length;){for(c=a+1;;)if(b.slice(c-1,+c+1||9E9),b.charAt(c-1)===b.charAt(c))c+=1;else{2<c-a&&e.push({pattern:"repeat",i:a,j:c-1,token:b.slice(a,c),repeated_char:b.charAt(a)});break}a=c}return e},function(b){var a,c,e,f,d,g,h,j,i,k,l,m,n;j=[];for(d=0;d<b.length;){g=d+1;m=n=i=null;for(l in w)if(k=w[l],e=function(){var c,e,f,h;f=[b.charAt(d),b.charAt(g)];h=[];c=0;for(e=f.length;c<e;c++)a=f[c],h.push(k.indexOf(a));return h}(),f=e[0],e=e[1],-1<f&&-1<e&&(f=e-f,1===
f||-1===f)){i=k;n=l;m=f;break}if(i)for(;;)if(f=b.slice(g-1,+g+1||9E9),h=f[0],c=f[1],e=function(){var b,d,e,f;e=[h,c];f=[];b=0;for(d=e.length;b<d;b++)a=e[b],f.push(k.indexOf(a));return f}(),f=e[0],e=e[1],e-f===m)g+=1;else{2<g-d&&j.push({pattern:"sequence",i:d,j:g-1,token:b.slice(d,g),sequence_name:n,sequence_space:i.length,ascending:1===m});break}d=g}return j},function(b){var a,c,e;e=[];for(c in F)a=F[c],y(e,U(b,a,c));return e}];F={qwerty:D,dvorak:{"!":["`~",null,null,"2@","'\"",null],'"':[null,"1!",
"2@",",<","aA",null],"#":["2@",null,null,"4$",".>",",<"],$:["3#",null,null,"5%","pP",".>"],"%":["4$",null,null,"6^","yY","pP"],"&":["6^",null,null,"8*","gG","fF"],"'":[null,"1!","2@",",<","aA",null],"(":["8*",null,null,"0)","rR","cC"],")":["9(",null,null,"[{","lL","rR"],"*":["7&",null,null,"9(","cC","gG"],"+":["/?","]}",null,"\\|",null,"-_"],",":"'\",2@,3#,.>,oO,aA".split(","),"-":["sS","/?","=+",null,null,"zZ"],".":",< 3# 4$ pP eE oO".split(" "),"/":"lL,[{,]},=+,-_,sS".split(","),"0":["9(",null,
null,"[{","lL","rR"],1:["`~",null,null,"2@","'\"",null],2:["1!",null,null,"3#",",<","'\""],3:["2@",null,null,"4$",".>",",<"],4:["3#",null,null,"5%","pP",".>"],5:["4$",null,null,"6^","yY","pP"],6:["5%",null,null,"7&","fF","yY"],7:["6^",null,null,"8*","gG","fF"],8:["7&",null,null,"9(","cC","gG"],9:["8*",null,null,"0)","rR","cC"],":":[null,"aA","oO","qQ",null,null],";":[null,"aA","oO","qQ",null,null],"<":"'\",2@,3#,.>,oO,aA".split(","),"=":["/?","]}",null,"\\|",null,"-_"],">":",< 3# 4$ pP eE oO".split(" "),
"?":"lL,[{,]},=+,-_,sS".split(","),"@":["1!",null,null,"3#",",<","'\""],A:[null,"'\"",",<","oO",";:",null],B:["xX","dD","hH","mM",null,null],C:"gG,8*,9(,rR,tT,hH".split(","),D:"iI,fF,gG,hH,bB,xX".split(","),E:"oO,.>,pP,uU,jJ,qQ".split(","),F:"yY,6^,7&,gG,dD,iI".split(","),G:"fF,7&,8*,cC,hH,dD".split(","),H:"dD,gG,cC,tT,mM,bB".split(","),I:"uU,yY,fF,dD,xX,kK".split(","),J:["qQ","eE","uU","kK",null,null],K:["jJ","uU","iI","xX",null,null],L:"rR,0),[{,/?,sS,nN".split(","),M:["bB","hH","tT","wW",null,
null],N:"tT,rR,lL,sS,vV,wW".split(","),O:"aA ,< .> eE qQ ;:".split(" "),P:".>,4$,5%,yY,uU,eE".split(","),Q:[";:","oO","eE","jJ",null,null],R:"cC,9(,0),lL,nN,tT".split(","),S:"nN,lL,/?,-_,zZ,vV".split(","),T:"hH,cC,rR,nN,wW,mM".split(","),U:"eE,pP,yY,iI,kK,jJ".split(","),V:["wW","nN","sS","zZ",null,null],W:["mM","tT","nN","vV",null,null],X:["kK","iI","dD","bB",null,null],Y:"pP,5%,6^,fF,iI,uU".split(","),Z:["vV","sS","-_",null,null,null],"[":["0)",null,null,"]}","/?","lL"],"\\":["=+",null,null,null,
null,null],"]":["[{",null,null,null,"=+","/?"],"^":["5%",null,null,"7&","fF","yY"],_:["sS","/?","=+",null,null,"zZ"],"`":[null,null,null,"1!",null,null],a:[null,"'\"",",<","oO",";:",null],b:["xX","dD","hH","mM",null,null],c:"gG,8*,9(,rR,tT,hH".split(","),d:"iI,fF,gG,hH,bB,xX".split(","),e:"oO,.>,pP,uU,jJ,qQ".split(","),f:"yY,6^,7&,gG,dD,iI".split(","),g:"fF,7&,8*,cC,hH,dD".split(","),h:"dD,gG,cC,tT,mM,bB".split(","),i:"uU,yY,fF,dD,xX,kK".split(","),j:["qQ","eE","uU","kK",null,null],k:["jJ","uU","iI",
"xX",null,null],l:"rR,0),[{,/?,sS,nN".split(","),m:["bB","hH","tT","wW",null,null],n:"tT,rR,lL,sS,vV,wW".split(","),o:"aA ,< .> eE qQ ;:".split(" "),p:".>,4$,5%,yY,uU,eE".split(","),q:[";:","oO","eE","jJ",null,null],r:"cC,9(,0),lL,nN,tT".split(","),s:"nN,lL,/?,-_,zZ,vV".split(","),t:"hH,cC,rR,nN,wW,mM".split(","),u:"eE,pP,yY,iI,kK,jJ".split(","),v:["wW","nN","sS","zZ",null,null],w:["mM","tT","nN","vV",null,null],x:["kK","iI","dD","bB",null,null],y:"pP,5%,6^,fF,iI,uU".split(","),z:["vV","sS","-_",
null,null,null],"{":["0)",null,null,"]}","/?","lL"],"|":["=+",null,null,null,null,null],"}":["[{",null,null,null,"=+","/?"],"~":[null,null,null,"1!",null,null]},keypad:E,mac_keypad:{"*":["/",null,null,null,null,null,"-","9"],"+":["6","9","-",null,null,null,null,"3"],"-":["9","/","*",null,null,null,"+","6"],".":["0","2","3",null,null,null,null,null],"/":["=",null,null,null,"*","-","9","8"],"0":[null,"1","2","3",".",null,null,null],1:[null,null,"4","5","2","0",null,null],2:["1","4","5","6","3",".",
"0",null],3:["2","5","6","+",null,null,".","0"],4:[null,null,"7","8","5","2","1",null],5:"4,7,8,9,6,3,2,1".split(","),6:["5","8","9","-","+",null,"3","2"],7:[null,null,null,"=","8","5","4",null],8:["7",null,"=","/","9","6","5","4"],9:"8,=,/,*,-,+,6,5".split(","),"=":[null,null,null,null,"/","9","8","7"]}};r=function(b){var a,c,e,f,d;a=0;for(e in b)d=b[e],a+=function(){var a,b,c;c=[];a=0;for(b=d.length;a<b;a++)(f=d[a])&&c.push(f);return c}().length;return a/=function(){var a;a=[];for(c in b)a.push(c);
return a}().length};pa=r(D);ra=r(E);oa=function(){var b;b=[];for(v in D)b.push(v);return b}().length;qa=function(){var b;b=[];for(v in E)b.push(v);return b}().length;G=function(){return(new Date).getTime()};r=function(b,a){var c,e;null==a&&(a=[]);e=G();c=R(b,sa.concat([H("user_inputs",I(a.map(function(a){return a.toLowerCase()})))]));c=ja(b,c);c.calc_time=G()-e;return c};"undefined"!==typeof window&&null!==window?(window.zxcvbn=r,"function"===typeof window.zxcvbn_load_hook&&window.zxcvbn_load_hook()):
"undefined"!==typeof exports&&null!==exports&&(exports.zxcvbn=r)})();
